name: Spring Boot Unit Testing

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Testing
        run: ./mvnw test
